version: '3.8'

services:
  mongo:
    image: mongo:4.4.18
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: student-rental-web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin"
      SPRING_REDIS_HOST: redis
      SPRING_PROFILES_ACTIVE: dev

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      LLM_SERVER_ADDRESS: ${LLM_SERVER_ADDRESS}
      LLM_SERVER_PORT: ${LLM_SERVER_PORT}

volumes:
  mongo-data:
