version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: student-rental-web
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SPRING_REDIS_HOST: redis
      SPRING_PROFILES_ACTIVE: dev

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      LLM_SERVER_ADDRESS: ${LLM_SERVER_ADDRESS}
      LLM_SERVER_PORT: ${LLM_SERVER_PORT}