spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379
      password: ""
      database: 0
  llm:
    server-address: ${LLM_SERVER_ADDRESS}
    server-port: ${LLM_SERVER_PORT}

server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework